services:
  - type: web
    name: mba-dm-service
    env: docker
    rootDir: dm-service
    plan: free
    region: frankfurt
    envVars:
      - key: API_KEY
        value: mba-brain-dm-2024
      - key: IG_USERNAME
        sync: false
      - key: IG_PASSWORD
        sync: false
      - key: FB_USERNAME
        sync: false
      - key: FB_PASSWORD
        sync: false
      - key: TT_USERNAME
        sync: false
      - key: TT_PASSWORD
        sync: false